import pyautogui
import time

pyautogui.press('winleft')
time.sleep(2)
pyautogui.write('firefox')
time.sleep(2)
pyautogui.press('enter')
time.sleep(2)
pyautogui.moveTo(324,119)
time.sleep(2)
pyautogui.click()
pyautogui.write('youtube one bit code')
time.sleep(2)
pyautogui.press('enter')
time.sleep(2)
pyautogui.moveTo(271,361)
time.sleep(2)
pyautogui.click()
time.sleep(2)
pyautogui.moveTo(682,583)
time.sleep(2)
pyautogui.click()
pyautogui.alert(text='Obrigado por se inscrever nesse canal', title='Agradecimento', button='OK')